apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-website
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devops-website
  template:
    metadata:
      labels:
        app: devops-website
    spec:
      containers:
        - name: devops-website
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 60
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 20