apiVersion: v1
kind: Service
metadata:
  name: devops-website
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: devops-website